# Generated by Django 4.1.6 on 2023-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='popular',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(default=1, max_length=3),
            preserve_default=False,
        ),
    ]
