# Generated by Django 4.1.6 on 2023-03-04 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blog_popular_blog_read_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='published_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='popular',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='read_time',
            field=models.IntegerField(),
        ),
    ]
